# Generated by Django 4.2.3 on 2023-07-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category',
        ),
    ]
