# Generated by Django 4.2.3 on 2023-07-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0002_rename_postcategory_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryThrough',
        ),
    ]
